services:

  Vancado\VncCancelForm\Command\CleanFolderCommand:
    tags:
      - name: 'console.command'
        command: 'vnccancelform:clearfolder'
        description: 'Clean powermail pdf folder'
